### ISSUE TITLE
Missing some config.js

### ISSUE THREAD

**Issue by PanRada** [piotrwitek/training-management-tool#1]
@piotrwitek During tests recognize in u repo is missing config.js. Just now on clone and run : npm, jsmp && typings instalation it is create default config.js with babel transpilation, but in this project is used Typescript.
This problem was checked on 2 Windows machine and on the Linux.

**!!important !!** Found solve problem - it not problem with config.js it is using jspm@beta(0.17) - wich suport Typescript

**Comment by piotrwitek** [comment]
config.js was used in jspm@0.16.X
in jspm@0.17.X there is jspm.config.js
project is using jspm@0.17
