### ISSUE TITLE
Add tooling for collaboration

### ISSUE THREAD

**Issue by piotrwitek** [piotrwitek/training-management-tool#15]
1. add editorconfig
2. add tslint rules to keep consistent code formating

**Comment by PanRada** [comment]
http://editorconfig.org/ 
maybe will good to catch that ?
week ago found on my arch,

**Comment by piotrwitek** [comment]
yes this is exactly what I was refering

**Comment by piotrwitek** [comment]
@82616ed6d1e5133ae7d7265c38c7f9ac2cbd9d3a
