### ISSUE TITLE
Add demo hosted on github pages

### ISSUE THREAD

**Issue by piotrwitek** [piotrwitek/training-management-tool#6]
Add demo hosted on github pages

**Comment by PanRada** [comment]
sound like good idea, but we must put some good json data for this project maybe we can use jslive.com for catch some

**Comment by piotrwitek** [comment]
IMO probably something more relevant to the topic will be better, like PluralSight

**Comment by PanRada** [comment]
... if PluralSight give us api with out registry, but yes is better that

**Comment by piotrwitek** [comment]
should be possible with rest api discovery if not look for another source
but relevant topic

Pozdrawiam,
Piotr Witek

2016-06-04 12:19 GMT+02:00 Pan Rada Production notifications@github.com:
